VERBOSE = False
TARGET = 'critical_temp'
FEATURE_CORRELATION_THRESHOLD = 0.5
FILENAME_SAVE_METRICS = "log/log_metrics"
FILENAME_SAVE_FEATURES = "log/log_features"
STRATEGIES_LIST = ['LinearRegression', 'KNeighborsRegressor', 'DecisionTreeRegressor', 'SVR']
#FEATURE_SELECTION_METHOD = 'wrapper'
FEATURE_SELECTION_METHOD = 'filter'
FEATURE_SELECTION_CUT_FRACTION = 0.5
